Notes.Web/Models/Note.cs
using Notes.Web.Models.CoreViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Notes.Web.Models
{
    public class Note
    {
        [Required, Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Body { get; set; }
        [Required]
        public DateTime CreatedAt { get; set; }
        [Required]
        public DateTime UpdatedAt { get; set; }

        [Required]
        public int NotebookId { get; set; }
        public virtual Notebook Notebook { get; set; }
    }
}

Notes.Web/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Notes.Web.Data;
using Notes.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Notes.Web.Models.CoreViewModels;
using Markdig;
using Notes.Web.Services;

namespace Notes.Web.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly GutenTag _gutenTag;

        public NotesController(ApplicationDbContext context, GutenTag gutenTag)
        {
            _context = context;
            _gutenTag = gutenTag;
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Notes.Include(n => n.Notebook);
            return View(await applicationDbContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes
                .Include(n => n.Notebook)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }
            var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
            note.Body = Markdown.ToHtml(note.Body, pipeline);
            return View(note);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int notebookId, NoteFormObject nfo)
        {
            if (ModelState.IsValid)
            {
                var note = nfo.CreateNote();
                note.NotebookId = notebookId;
                _context.Add(note);
                await _context.SaveChangesAsync();
                if (!string.IsNullOrWhiteSpace(nfo.TagList))
                {
                    await _gutenTag.AddToDb(new TagHolder(note.Id, "Note", nfo.TagList));
                }
                return RedirectToAction("Details", new { NotebookId = notebookId, Id = note.Id });
            }
            return View(nfo);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes.SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }
            var tagList = await _context.TagItems.Include(ti => ti.Tag)
                .Where(ti => ti.ItemId == note.Id && ti.ItemType == ItemType.Note).ToListAsync();
            return View(new NoteFormObject(note, tagList.Select(ti => ti.Tag.Name).ToList()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NoteFormObject nfo)
        {
            var note = await _context.Notes.FindAsync(id);

            if (ModelState.IsValid)
            {
                nfo.UpdateNote(note);
                _context.Update(note);
                await _context.SaveChangesAsync();
                if (!string.IsNullOrWhiteSpace(nfo.TagList))
                {
                    await _gutenTag.AddToDb(new TagHolder(note.Id, "Note", nfo.TagList));
                }
                return RedirectToAction("Details", new { Id = note.Id });
            }
            return View(nfo);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes
                .Include(n => n.Notebook)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Notes.SingleOrDefaultAsync(m => m.Id == id);
            _context.Notes.Remove(note);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Notebooks", new { Id = note.NotebookId });
        }

        private bool NoteExists(int id)
        {
            return _context.Notes.Any(e => e.Id == id);
        }
    }
}

Notes.Web/Views/Notes/Create.cshtml
@model NoteFormObject

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form id="NoteForm" asp-action="Create">
    @await Html.PartialAsync("_Form")
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Notes.Web/Views/Notes/Delete.cshtml
@model Notes.Web.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notebook)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notebook.ApplicationUserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Notes.Web/Views/Notes/Details.cshtml
@model Note

@{
    ViewData["Title"] = "Details";
}

<h2>
    @Model.Name
    <small>
        <a asp-action="Details" asp-controller="Notebooks" asp-route-id="@Model.NotebookId">@Model.Notebook.Name</a>
    </small>
</h2>
<ul class="list-inline">
    <li>
        <b>Created</b>
        @Model.CreatedAt
    </li>
    <li>
        <b>Latest Update</b>
        @Model.UpdatedAt
    </li>
    <li>
        <a asp-action="Edit" asp-controller="Notes" asp-route-notebookId="@Model.NotebookId" asp-route-id="@Model.Id">Edit</a>
    </li>
    <li>
        <a asp-action="Delete" asp-controller="Notes" asp-route-notebookId="@Model.NotebookId" asp-route-id="@Model.Id">Delete</a>
    </li>
</ul>
<div class="note-body">
    @Html.Raw(Model.Body)
</div>

Notes.Web/Views/Notes/Edit.cshtml
@model NoteFormObject

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form id="NoteForm" asp-action="Edit">
    @await Html.PartialAsync("_Form")
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Notes.Web/Views/Notes/Index.cshtml
@model IEnumerable<Notes.Web.Models.Note>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Body)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedAt)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Notebook)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notebook.ApplicationUserId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Notes.Web/Views/Notes/_Form.cshtml
@model NoteFormObject

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Body" class="control-label"></label>
    <textarea asp-for="Body" class="form-control"></textarea>
    <span asp-validation-for="Body" class="text-danger"></span>
</div>
<div id="NoteEditor"></div>
<div class="form-group">
    <label asp-for="TagList" class="control-label"></label>
    <input asp-for="TagList" class="form-control" />
    <span asp-validation-for="TagList" class="text-danger"></span>
</div>